// Copyright 2025 The Ray Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package metrics

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"

	"github.com/ray-project/ray/go/internal/dashboard/head"
)

func newTestMetrics() *MetricsHead {
	return New(&head.HeadConfig{}, nil)
}

func serveHealth(t *testing.T, m *MetricsHead, path string) *httptest.ResponseRecorder {
	t.Helper()
	mux := http.NewServeMux()
	if err := m.RegisterHTTP(mux); err != nil {
		t.Fatal(err)
	}
	req := httptest.NewRequest("GET", path, nil)
	rr := httptest.NewRecorder()
	mux.ServeHTTP(rr, req)
	return rr
}

func TestMetricsHeadName(t *testing.T) {
	m := newTestMetrics()
	if m.Name() != "MetricsHead" {
		t.Fatalf("name = %q", m.Name())
	}
	if !m.Healthy() {
		t.Fatal("should be healthy")
	}
	if err := m.Start(context.Background()); err != nil {
		t.Fatal(err)
	}
}

func TestGrafanaHealthOK(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/api/health" {
			t.Fatalf("path = %q, want /api/health", r.URL.Path)
		}
		w.Write([]byte(`{"database":"ok"}`))
	}))
	defer srv.Close()

	m := New(&head.HeadConfig{SessionName: "session_test"}, nil)
	m.grafanaHost = srv.URL
	rr := serveHealth(t, m, "/api/grafana_health")
	if rr.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200, body=%s", rr.Code, rr.Body.String())
	}
	body := rr.Body.String()
	if !contains(body, `"result": true`) || !contains(body, `"msg": "Grafana running"`) {
		t.Fatalf("body = %s", body)
	}
	// The success response carries session_name and dashboard_uids, aligned
	// with metrics_head.py. The six default dashboard uids match the values
	// generated by _create_default_grafana_configs.
	if !contains(body, `"sessionName": "session_test"`) {
		t.Fatalf("body missing sessionName: %s", body)
	}
	for _, uid := range []string{
		`"default": "rayDefaultDashboard"`,
		`"serve": "rayServeDashboard"`,
		`"serveDeployment": "rayServeDeploymentDashboard"`,
		`"serveLlm": "rayServeLlmDashboard"`,
		`"data": "rayDataDashboard"`,
		`"train": "rayTrainDashboard"`,
	} {
		if !contains(body, uid) {
			t.Fatalf("body missing dashboard uid %s: %s", uid, body)
		}
	}
	// The grafana_host reflects the iframe host (defaults to grafana host).
	if !contains(body, `"grafanaHost": "`+srv.URL+`"`) {
		t.Fatalf("body missing grafanaHost: %s", body)
	}
}

func TestGrafanaHealthIframeHost(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`{"database":"ok"}`))
	}))
	defer srv.Close()

	m := New(&head.HeadConfig{}, nil)
	m.grafanaHost = srv.URL
	m.grafanaIframeHost = "https://grafana.example.com"
	rr := serveHealth(t, m, "/api/grafana_health")
	if rr.Code != http.StatusOK {
		t.Fatalf("status = %d", rr.Code)
	}
	body := rr.Body.String()
	if !contains(body, `"grafanaHost": "https://grafana.example.com"`) {
		t.Fatalf("body missing iframe host: %s", body)
	}
}

func TestGrafanaHealthDBNotOK(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`{"database":"not ok"}`))
	}))
	defer srv.Close()

	m := newTestMetrics()
	m.grafanaHost = srv.URL
	rr := serveHealth(t, m, "/api/grafana_health")
	if rr.Code != http.StatusInternalServerError {
		t.Fatalf("status = %d, want 500", rr.Code)
	}
}

func TestGrafanaHealthError503(t *testing.T) {
	// A server that closes immediately -> connection error -> 500 (aligned with
	// the Python INTERNAL_ERROR on exception).
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
	srv.Close()

	m := newTestMetrics()
	m.grafanaHost = srv.URL
	rr := serveHealth(t, m, "/api/grafana_health")
	if rr.Code != http.StatusInternalServerError {
		t.Fatalf("status = %d, want 500", rr.Code)
	}
}

func TestGrafanaHealthDisabled(t *testing.T) {
	m := newTestMetrics()
	m.grafanaHost = grafanaHostDisabledValue
	rr := serveHealth(t, m, "/api/grafana_health")
	if rr.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", rr.Code)
	}
	if body := rr.Body.String(); !contains(body, "DISABLED") {
		t.Fatalf("body = %s", body)
	}
}

func TestPrometheusHealthOK(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/-/healthy" {
			t.Fatalf("path = %q, want /-/healthy", r.URL.Path)
		}
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	m := newTestMetrics()
	m.prometheusHost = srv.URL
	rr := serveHealth(t, m, "/api/prometheus_health")
	if rr.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", rr.Code)
	}
}

func TestPrometheusHealthSendsHeaders(t *testing.T) {
	var gotHeader string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotHeader = r.Header.Get("X-Prom-Auth")
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	m := New(&head.HeadConfig{}, nil)
	m.prometheusHost = srv.URL
	m.prometheusHeaders = map[string]string{"X-Prom-Auth": "secret"}
	rr := serveHealth(t, m, "/api/prometheus_health")
	if rr.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", rr.Code)
	}
	if gotHeader != "secret" {
		t.Fatalf("prometheus header = %q, want secret", gotHeader)
	}
}

func TestPrometheusHealthFailure(t *testing.T) {
	m := newTestMetrics()
	m.prometheusHost = "http://127.0.0.1:1"
	rr := serveHealth(t, m, "/api/prometheus_health")
	if rr.Code != http.StatusInternalServerError {
		t.Fatalf("status = %d, want 500", rr.Code)
	}
}

func TestEnvConfig(t *testing.T) {
	os.Setenv("RAY_GRAFANA_HOST", "http://grafana:3000")
	os.Setenv("RAY_PROMETHEUS_HOST", "http://prom:9090")
	os.Setenv("RAY_GRAFANA_ORG_ID", "42")
	defer os.Unsetenv("RAY_GRAFANA_HOST")
	defer os.Unsetenv("RAY_PROMETHEUS_HOST")
	defer os.Unsetenv("RAY_GRAFANA_ORG_ID")

	m := newTestMetrics()
	if m.grafanaHost != "http://grafana:3000" || m.prometheusHost != "http://prom:9090" || m.grafanaOrgID != "42" {
		t.Fatalf("env config not applied: %+v", m)
	}
}

func contains(s, sub string) bool {
	return len(s) >= len(sub) && indexOf(s, sub) >= 0
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}
