load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "usage_stats",
    srcs = ["usage_stats.go"],
    importpath = "github.com/ray-project/ray/go/internal/dashboard/head/modules/usage_stats",
    visibility = ["//go:__subpackages__"],
    deps = [
        "//go/internal/dashboard/head",
    ],
)

go_test(
    name = "usage_stats_test",
    srcs = ["usage_stats_test.go"],
    embed = [":usage_stats"],
    deps = [
        "//go/internal/dashboard/head",
    ],
)
