load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "node",
    srcs = [
        "datacenter.go",
        "node.go",
    ],
    importpath = "github.com/ray-project/ray/go/internal/dashboard/head/modules/node",
    visibility = ["//go:__subpackages__"],
    deps = [
        "//go/internal/dashboard/head",
        "//go/pkg/log",
        "//go/proto",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_test(
    name = "node_test",
    srcs = ["node_test.go"],
    embed = [":node"],
    deps = [
        "//go/internal/dashboard/head",
        "//go/proto",
        "@org_golang_google_grpc//:go_default_library",
    ],
)
