// Copyright 2025 The Ray Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Hand-maintained LogService gRPC server stubs.
//
// go/proto is generated with go_proto_compile (messages only, no gRPC stubs)
// so that go_runtime.so does not link the gRPC stack. This package is the only
// consumer of the LogService server-side stub, so the stub lives here instead
// of in go/proto. It mirrors the code previously generated by protoc-gen-go's
// plugins=grpc for the LogService service in src/ray/protobuf/reporter.proto.
package log

import (
	"context"

	"github.com/ray-project/ray/go/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// LogServiceServer is the server API for LogService service.
type LogServiceServer interface {
	ListLogs(context.Context, *proto.ListLogsRequest) (*proto.ListLogsReply, error)
	StreamLog(*proto.StreamLogRequest, LogService_StreamLogServer) error
}

// UnimplementedLogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct{}

func (*UnimplementedLogServiceServer) ListLogs(context.Context, *proto.ListLogsRequest) (*proto.ListLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLogs not implemented")
}
func (*UnimplementedLogServiceServer) StreamLog(*proto.StreamLogRequest, LogService_StreamLogServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLog not implemented")
}

func RegisterLogServiceServer(s *grpc.Server, srv LogServiceServer) {
	s.RegisterService(&_LogService_serviceDesc, srv)
}

func _LogService_ListLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.ListLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ListLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ray.rpc.LogService/ListLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ListLogs(ctx, req.(*proto.ListLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_StreamLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto.StreamLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServiceServer).StreamLog(m, &logServiceStreamLogServer{stream})
}

// LogService_StreamLogServer is the server-side stream for the StreamLog RPC.
type LogService_StreamLogServer interface {
	Send(*proto.StreamLogReply) error
	grpc.ServerStream
}

type logServiceStreamLogServer struct {
	grpc.ServerStream
}

func (x *logServiceStreamLogServer) Send(m *proto.StreamLogReply) error {
	return x.ServerStream.SendMsg(m)
}

var _LogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ray.rpc.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLogs",
			Handler:    _LogService_ListLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLog",
			Handler:       _LogService_StreamLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/ray/protobuf/reporter.proto",
}
